// lib/verses.ts
//
// A curated bank. Scripture is NEVER generated by the AI — the AI only
// selects from what is written here, so nothing can be misquoted or invented.
//
// TRANSLATION: renderings below follow the World English Bible (WEB), which is
// public domain. VERIFY each one against a WEB text before shipping. Do not
// substitute NIV/ESV/NLT wording — those require a commercial licence.

export type Verse = {
  text: string;
  ref: string;
  dimension: 'Spirit' | 'Physical' | 'Intellect' | 'Relationship' | 'Income' | 'Transcendence';
  sem: number[]; // which Formation Stages this suits
};

export const VERSES: Verse[] = [
  // ---------- SPIRIT ----------
  {
    text: 'Yahweh is near to those who have a broken heart, and saves those who have a crushed spirit.',
    ref: 'Psalm 34:18',
    dimension: 'Spirit',
    sem: [0, 1],
  },
  {
    text: 'Come to me, all you who labor and are heavily burdened, and I will give you rest.',
    ref: 'Matthew 11:28',
    dimension: 'Spirit',
    sem: [0, 1],
  },
  {
    text: 'Be still, and know that I am God.',
    ref: 'Psalm 46:10',
    dimension: 'Spirit',
    sem: [0, 1, 2],
  },
  {
    text: 'Your word is a lamp to my feet, and a light for my path.',
    ref: 'Psalm 119:105',
    dimension: 'Spirit',
    sem: [1, 2],
  },
  {
    text: 'Draw near to God, and he will draw near to you.',
    ref: 'James 4:8',
    dimension: 'Spirit',
    sem: [1, 2, 3],
  },
  {
    text: 'But seek first God\u2019s Kingdom and his righteousness; and all these things will be given to you as well.',
    ref: 'Matthew 6:33',
    dimension: 'Spirit',
    sem: [2, 3],
  },

  // ---------- PHYSICAL ----------
  {
    text: 'He gives power to the weak. He increases the strength of him who has no might.',
    ref: 'Isaiah 40:29',
    dimension: 'Physical',
    sem: [0, 1],
  },
  {
    text: 'It is vain for you to rise up early, to stay up late, eating the bread of toil; for he gives sleep to his loved ones.',
    ref: 'Psalm 127:2',
    dimension: 'Physical',
    sem: [0, 1],
  },
  {
    text: 'Don\u2019t you know that your body is a temple of the Holy Spirit who is in you?',
    ref: '1 Corinthians 6:19',
    dimension: 'Physical',
    sem: [1, 2],
  },
  {
    text: 'Whether therefore you eat, or drink, or whatever you do, do all to the glory of God.',
    ref: '1 Corinthians 10:31',
    dimension: 'Physical',
    sem: [2, 3],
  },

  // ---------- INTELLECT ----------
  {
    text: 'If any of you lacks wisdom, let him ask of God, who gives to all liberally and without reproach.',
    ref: 'James 1:5',
    dimension: 'Intellect',
    sem: [0, 1, 2],
  },
  {
    text: 'Trust in Yahweh with all your heart, and don\u2019t lean on your own understanding.',
    ref: 'Proverbs 3:5',
    dimension: 'Intellect',
    sem: [0, 1, 2],
  },
  {
    text: 'The fear of Yahweh is the beginning of knowledge.',
    ref: 'Proverbs 1:7',
    dimension: 'Intellect',
    sem: [1, 2],
  },
  {
    text: 'Be transformed by the renewing of your mind.',
    ref: 'Romans 12:2',
    dimension: 'Intellect',
    sem: [2, 3],
  },

  // ---------- RELATIONSHIP ----------
  {
    text: 'Two are better than one, because they have a good reward for their labor.',
    ref: 'Ecclesiastes 4:9',
    dimension: 'Relationship',
    sem: [0, 1, 2],
  },
  {
    text: 'A friend loves at all times; and a brother is born for adversity.',
    ref: 'Proverbs 17:17',
    dimension: 'Relationship',
    sem: [0, 1, 2],
  },
  {
    text: 'Bear one another\u2019s burdens, and so fulfill the law of Christ.',
    ref: 'Galatians 6:2',
    dimension: 'Relationship',
    sem: [1, 2, 3],
  },
  {
    text: 'Be kind to one another, tender hearted, forgiving each other.',
    ref: 'Ephesians 4:32',
    dimension: 'Relationship',
    sem: [1, 2],
  },
  {
    text: 'As iron sharpens iron, so a man sharpens his friend\u2019s countenance.',
    ref: 'Proverbs 27:17',
    dimension: 'Relationship',
    sem: [2, 3],
  },

  // ---------- INCOME ----------
  {
    text: 'My God will supply every need of yours according to his riches in glory in Christ Jesus.',
    ref: 'Philippians 4:19',
    dimension: 'Income',
    sem: [0, 1],
  },
  {
    text: 'Therefore don\u2019t be anxious for tomorrow, for tomorrow will be anxious for itself.',
    ref: 'Matthew 6:34',
    dimension: 'Income',
    sem: [0, 1],
  },
  {
    text: 'Whatever you do, work heartily, as for the Lord, and not for men.',
    ref: 'Colossians 3:23',
    dimension: 'Income',
    sem: [1, 2],
  },
  {
    text: 'Commit your deeds to Yahweh, and your plans shall succeed.',
    ref: 'Proverbs 16:3',
    dimension: 'Income',
    sem: [2, 3],
  },

  // ---------- TRANSCENDENCE ----------
  {
    text: 'Even so, let your light shine before men, that they may see your good works.',
    ref: 'Matthew 5:16',
    dimension: 'Transcendence',
    sem: [1, 2, 3],
  },
  {
    text: 'Most certainly I tell you, because you did it to one of the least of these my brothers, you did it to me.',
    ref: 'Matthew 25:40',
    dimension: 'Transcendence',
    sem: [2, 3],
  },
  {
    text: 'As each has received a gift, employ it in serving one another.',
    ref: '1 Peter 4:10',
    dimension: 'Transcendence',
    sem: [2, 3],
  },
  {
    text: 'Freely you received, so freely give.',
    ref: 'Matthew 10:8',
    dimension: 'Transcendence',
    sem: [2, 3],
  },
];

// Stable per day: the same person gets the same verse all day, a new one tomorrow.
function daySeed(uid: string) {
  const day = new Date().toISOString().slice(0, 10);
  let h = 0;
  for (const c of day + uid) h = (h * 31 + c.charCodeAt(0)) | 0;
  return Math.abs(h);
}

export function pickVerse(params: {
  uid: string;
  semLevel: number;
  dimension?: string;
  exclude?: string[]; // refs seen recently
}): Verse {
  const { uid, semLevel, dimension, exclude = [] } = params;

  const fits = (v: Verse) => v.sem.includes(semLevel) && !exclude.includes(v.ref);

  // 1. the dimension they have been living in, at their stage
  let pool = VERSES.filter((v) => v.dimension === dimension && fits(v));
  // 2. anything at their stage
  if (!pool.length) pool = VERSES.filter(fits);
  // 3. Spirit is always the fallback — it never switches off
  if (!pool.length) pool = VERSES.filter((v) => v.dimension === 'Spirit');

  return pool[daySeed(uid) % pool.length];
}